import './style/index.scss'

import './controls/play.js'
import './controls/start.js'
import './controls/poster.js'
import './controls/flex.js'
import './controls/fullscreen.js'
import './controls/cssFullscreen.js'
// import './controls/volume.js'
import './controls/definition.js'
import './controls/displayMode.js'
import './controls/loading.js'
import './controls/progress.js'
import './controls/time.js'
import './controls/replay.js'
import './controls/version.js'
